### ISSUE TITLE
`neosNext` path is not configured for any PreviewMode

### ISSUE THREAD

**Issue by johannessteu** [networkteam/Networkteam.Neos.Next#3]
This package should either include a preview Mode set to fusionPath `neosNext` or add some hints to the readme to enable the oob rendering

**Comment by networkteam-lange** [comment]
The PreviewMode should actually work. We only have to handle `isEditingMode: FALSE` and `Raw Content` on a special way. This is still missing.

**Comment by hlubek** [comment]
I'm not sure all these things are actually the same issue ;)

Regarding preview mode: Since we just rewrite the URL to the preview (e.g. `/neos/preview?node[__contextNodePath]=/sites/site/node-1tofgrjjhgn9y@user-admin;language=en`) to be handled by a Next.js route and the Neos UI doesn't add anything to that URL for the current preview mode, we need to handle the current user preference in Next.js in the result from the content API (at least that's what I think). So we can correctly disable editing even though we are `inBackend`. I started to implement this in the ContentApi (https://github.com/networkteam/Networkteam.Neos.ContentApi/commit/9dbb20a88879aa23ae41b9ad17beea9026fcc5d2) and Zebra packages (https://github.com/networkteam/zebra/commit/da1ed5f2c7d889f2575d144950273b052fd41d2f).

Regarding raw content mode: Supporting it would mean to use the frontend rendering on Neos and thus going back from Next.js to Neos in that case. Maybe we should rather implement it completely in Zebra with a few generic components?

@johannessteu If you access Neos via Next.js (using `@networkteam/zebra`) the fusion path isn't actually used anywhere, since the `Frontend/NodeController` isn't called in the backend. The OOB is mainly used via `PreviewNodeImplementation` to fetch a rendered node from Next.js to send it back to the Neos UI (which feels a bit of a workaround, since we found this to not be extensible in the Neos UI for now). Could you explain your case a bit more?

**Comment by johannessteu** [comment]
hey, yeah i guess i mixed this up. The demo is not working for me right now and i tried to debug and opened this via Neos and then was looking how to get the next pages. I over read that neos should only be accessed via next!
